---
- name: get mattermost from github
  unarchive: 
    src: https://releases.mattermost.com/{{mattermost_version}}/mattermost-team-{{mattermost_version}}-linux-amd64.tar.gz
    dest: /opt
    copy: no

- name: create mattermost user
  user: 
    name: "{{ mattermost_user }}"
    system: yes
    createhome: no

- name: create mattermost init script
  template:
    src: init_script.ec2
    dest: /etc/init.d/mattermost
    owner: root
    group: root
    mode: 0755

- name: edit /opt/mattermost/config/config.json
  lineinfile:
    dest: /opt/mattermost/config/config.json
    regexp: '"DriverName": "mysql",'
    line: '        "DriverName": "postgres",'

- name: edit /opt/mattermost/config/config.json
  lineinfile:
    dest: /opt/mattermost/config/config.json
    regexp: '"DataSource":'
    line: '        "DataSource": "postgres://{{ db_user }}:{{ db_password }}@127.0.0.1:5432/{{ db_name }}?sslmode=disable&connect_timeout=10",'

- name: change mattermost directory permissions
  file:
    path: /opt/mattermost
    state: directory
    owner: "{{ mattermost_user }}"
    group: "{{ mattermost_user }}"
    recurse: yes
  notify: start mattermost
